import { CompanyProfile, TenderSpec } from "./types";

/** Digital Twin used until the user completes onboarding. */
export const DEMO_COMPANY: CompanyProfile = {
  name: 'ТОО "Алтын Логистик"',
  workingCapital: 52_000_000,
  maxDistanceKm: 900,
  staffSize: 24,
  baseCityId: "almaty",
  taxRegime: "vat",
  monthlyOpex: 4_200_000,
  opexAllocation: 0.35,
  creditRate: 0.24,
  experienceYears: 4,
  certificates: ["ISO 9001", "СТ РК"],
  // Valid check digit; fictitious company.
  bin: "180540012343",
  directorName: "Ахметов Арман Болатұлы",
  phone: "+77010000000",
  telegramUsername: "",
  legalAddress: "Алматы, Бостандық ауданы",
};

/**
 * Demo lots — the exact shape the goszakup adapter + Layer 1 parser must produce.
 * `specPages` stand in for the parsed PDF so the chatbot can quote real clauses.
 */
export const DEMO_GOSZAKUP: TenderSpec[] = [
  {
    id: "goszakup-700417-ОК1",
    externalId: "700417-ОК1",
    source: "goszakup",
    sourceUrl: "https://goszakup.gov.kz",
    isDemo: true,
    estimated: false,
    titleKz: "Облыстық мектептерге компьютерлік жабдық жеткізу",
    advancePercentage: 0,
    title: "Поставка компьютерного оборудования для областных школ",
    customer: "Управление образования области Жетісу",
    contractAmount: 84_000_000,
    deliveryDays: 30,
    paymentDelayDays: 30,
    penaltyRate: 0.001,
    purchaseCost: 62_000_000,
    cityId: "taldykorgan",
    cargoTonnes: 14,
    requiredExperienceYears: 3,
    requiredCertificates: ["ISO 9001"],
    hiddenRequirements: [],
    deadline: "2026-09-24",
    specPages: [
      { page: 1, text: "Предмет закупки: персональные компьютеры в сборе (моноблоки) — 420 шт., интерактивные панели 75\" — 38 шт. Место поставки: г. Талдыкорган, склад заказчика." },
      { page: 4, text: "Срок поставки: 30 календарных дней с даты заключения договора. Поставка единовременная. Разгрузка силами поставщика." },
      { page: 7, text: "Оплата: 100% в течение 30 календарных дней с даты подписания акта приёма-передачи. Авансовый платёж не предусмотрен." },
      { page: 9, text: "За просрочку поставки поставщик уплачивает неустойку 0,1% от общей суммы договора за каждый день просрочки, но не более 10%." },
      { page: 12, text: "Гарантийный срок — 36 месяцев. Сервисный центр в радиусе 300 км от места поставки. Сертификат ISO 9001 производителя обязателен." },
    ],
  },
  {
    id: "goszakup-700388-ОК1",
    externalId: "700388-ОК1",
    source: "goszakup",
    sourceUrl: "https://goszakup.gov.kz",
    isDemo: true,
    estimated: false,
    titleKz: "Аудандық аурухананың шатырын күрделі жөндеу",
    advancePercentage: 0,
    title: "Капитальный ремонт кровли районной больницы",
    customer: "ГКП «Больница №4»",
    contractAmount: 145_000_000,
    deliveryDays: 75,
    paymentDelayDays: 60,
    penaltyRate: 0.003,
    purchaseCost: 112_000_000,
    cityId: "aktobe",
    cargoTonnes: 180,
    requiredExperienceYears: 5,
    requiredCertificates: ["ISO 9001", "ISO 45001", "Лицензия СМР III"],
    hiddenRequirements: [
      {
        clause: "Наличие собственного асфальтобетонного завода в радиусе 30 км от объекта",
        page: 12,
        severity: "high",
        reason: "собственный завод в радиусе 30 км отсекает всех, кроме местного игрока",
      },
      {
        clause: "Опыт по 3 аналогичным объектам именно в Актюбинской области",
        page: 14,
        severity: "medium",
        reason: "региональная привязка опыта не предусмотрена типовой документацией",
      },
    ],
    deadline: "2026-09-19",
    specPages: [
      { page: 2, text: "Объём работ: демонтаж и монтаж кровли 4 200 м², замена водостоков, утепление. Материалы поставщика." },
      { page: 6, text: "Срок выполнения работ: 75 календарных дней. Оплата: в течение 60 дней после подписания акта выполненных работ." },
      { page: 9, text: "Неустойка за нарушение сроков — 0,3% от суммы договора за каждый день просрочки." },
      { page: 12, text: "Потенциальный поставщик обязан иметь собственный асфальтобетонный завод в радиусе 30 км от объекта." },
      { page: 14, text: "Требуется опыт выполнения не менее 3 аналогичных работ на территории Актюбинской области за последние 5 лет." },
    ],
  },
  {
    id: "goszakup-700451-ОК1",
    externalId: "700451-ОК1",
    source: "goszakup",
    sourceUrl: "https://goszakup.gov.kz",
    isDemo: true,
    estimated: false,
    titleKz: "Кеңсе тауарлары мен шығын материалдарын жеткізу",
    advancePercentage: 0,
    title: "Поставка канцелярских товаров и расходных материалов",
    customer: "Аппарат акима г. Алматы",
    contractAmount: 12_400_000,
    deliveryDays: 20,
    paymentDelayDays: 15,
    penaltyRate: 0.001,
    purchaseCost: 8_900_000,
    cityId: "almaty",
    cargoTonnes: 3,
    requiredExperienceYears: 1,
    requiredCertificates: [],
    hiddenRequirements: [],
    deadline: "2026-09-12",
    specPages: [
      { page: 1, text: "Бумага А4 — 2 400 пачек, картриджи — 180 шт., канцелярские наборы — 600 шт." },
      { page: 3, text: "Поставка в течение 20 календарных дней, партиями по заявке заказчика. Оплата в течение 15 дней после поставки." },
    ],
  },
  {
    id: "goszakup-700402-ОК1",
    externalId: "700402-ОК1",
    source: "goszakup",
    sourceUrl: "https://goszakup.gov.kz",
    isDemo: true,
    estimated: false,
    titleKz: "Ауылдық амбулаторияларға дәрі-дәрмек жеткізу",
    advancePercentage: 0,
    title: "Поставка медикаментов для сельских амбулаторий",
    customer: "Управление здравоохранения Жамбылской области",
    contractAmount: 96_000_000,
    deliveryDays: 45,
    paymentDelayDays: 90,
    penaltyRate: 0.001,
    purchaseCost: 71_000_000,
    cityId: "taraz",
    cargoTonnes: 22,
    requiredExperienceYears: 3,
    requiredCertificates: ["GDP", "ISO 9001"],
    hiddenRequirements: [
      {
        clause: "Срок поставки по каждой заявке — 5 календарных дней",
        page: 8,
        severity: "medium",
        reason: "нереалистичное окно поставки при 90-дневной отсрочке оплаты",
      },
    ],
    deadline: "2026-09-27",
    specPages: [
      { page: 3, text: "Номенклатура: 64 наименования лекарственных средств согласно приложению 1. Хранение при +2…+8 °C для 11 позиций." },
      { page: 8, text: "Поставка по заявкам заказчика, срок исполнения каждой заявки — 5 календарных дней." },
      { page: 10, text: "Оплата производится в течение 90 календарных дней с даты поставки." },
    ],
  },
  {
    id: "goszakup-700433-ОК1",
    externalId: "700433-ОК1",
    source: "goszakup",
    sourceUrl: "https://goszakup.gov.kz",
    isDemo: true,
    estimated: false,
    titleKz: "ҚТҚ шығару және кәдеге жарату қызметтері",
    advancePercentage: 0,
    title: "Услуги по вывозу и утилизации ТБО",
    customer: "Отдел ЖКХ г. Шымкент",
    contractAmount: 58_000_000,
    deliveryDays: 180,
    paymentDelayDays: 30,
    penaltyRate: 0.001,
    purchaseCost: 34_000_000,
    cityId: "shymkent",
    cargoTonnes: 20,
    requiredExperienceYears: 2,
    requiredCertificates: ["ISO 14001"],
    hiddenRequirements: [],
    deadline: "2026-10-02",
    specPages: [
      { page: 2, text: "Вывоз ТБО с 140 контейнерных площадок, график — ежедневно. Срок оказания услуг — 180 дней." },
      { page: 5, text: "Оплата ежемесячно в течение 30 дней после подписания акта оказанных услуг." },
    ],
  },
  {
    id: "goszakup-700460-ОК1",
    externalId: "700460-ОК1",
    source: "goszakup",
    sourceUrl: "https://goszakup.gov.kz",
    isDemo: true,
    estimated: false,
    titleKz: "Коммуналдық қызметтерге арнайы киім жеткізу",
    advancePercentage: 0,
    title: "Поставка спецодежды для коммунальных служб",
    customer: "ГКП «Тазалык»",
    contractAmount: 31_500_000,
    deliveryDays: 25,
    paymentDelayDays: 45,
    penaltyRate: 0.0015,
    purchaseCost: 25_800_000,
    cityId: "karaganda",
    cargoTonnes: 6,
    requiredExperienceYears: 2,
    requiredCertificates: ["СТ РК"],
    hiddenRequirements: [
      {
        clause: "Ткань артикул TX-4471-KZ производства одной фабрики",
        page: 6,
        severity: "high",
        reason: "артикул ткани подходит продукции ровно одного поставщика",
      },
    ],
    deadline: "2026-09-21",
    specPages: [
      { page: 2, text: "Костюмы летние — 1 200 комплектов, зимние — 800 комплектов, сигнальные жилеты — 2 000 шт." },
      { page: 6, text: "Ткань верха: строго артикул TX-4471-KZ, плотность 245 г/м². Аналоги не допускаются." },
      { page: 9, text: "Оплата в течение 45 дней после поставки. Неустойка 0,15% в день." },
    ],
  },
];

/**
 * Demo lots for platforms without a public API. Shape and terms are realistic for each
 * platform; links point to the portal home because these lots are not real listings.
 */
export const DEMO_OTHER_PLATFORMS: TenderSpec[] = [
  {
    id: "samruk-SK-2026-18844",
    externalId: "SK-2026-18844",
    source: "samruk",
    sourceUrl: "https://zakup.sk.kz",
    isDemo: true,
    estimated: false,
    title: "Поставка запасных частей для тягового подвижного состава",
    titleKz: "Тартқыш жылжымалы құрамға қосалқы бөлшектер жеткізу",
    customer: "АО «ҚТЖ — Грузовые перевозки»",
    contractAmount: 212_000_000,
    advancePercentage: 30,
    deliveryDays: 60,
    paymentDelayDays: 30,
    penaltyRate: 0.001,
    purchaseCost: 171_000_000,
    cityId: "astana",
    cargoTonnes: 36,
    requiredExperienceYears: 3,
    requiredCertificates: ["ISO 9001", "СТ-KZ"],
    hiddenRequirements: [],
    deadline: "2026-09-29",
    specPages: [
      { page: 2, text: "Номенклатура: тормозные колодки, фильтры, подшипники буксовые — 214 позиций согласно приложению 1." },
      { page: 5, text: "Аванс 30% в течение 10 рабочих дней после подписания договора. Окончательный расчёт — 30 дней после поставки." },
      { page: 8, text: "Приоритет отечественным товаропроизводителям: требуется сертификат происхождения СТ-KZ." },
    ],
  },
  {
    id: "nadloc-NL-2026-3317",
    externalId: "NL-2026-3317",
    source: "nadloc",
    sourceUrl: "https://reestr.nadloc.kz",
    isDemo: true,
    estimated: false,
    title: "Услуги геологоразведочного бурения скважин",
    titleKz: "Геологиялық барлау ұңғымаларын бұрғылау қызметтері",
    customer: "ТОО «Недропользователь Сарыарка»",
    contractAmount: 178_000_000,
    advancePercentage: 0,
    deliveryDays: 120,
    paymentDelayDays: 45,
    penaltyRate: 0.001,
    purchaseCost: 128_000_000,
    cityId: "karaganda",
    cargoTonnes: 60,
    requiredExperienceYears: 5,
    requiredCertificates: ["ISO 45001", "Лицензия на бурение"],
    hiddenRequirements: [
      {
        clause: "Наличие не менее 4 буровых установок в собственности (не аренда)",
        page: 6,
        severity: "medium",
        reason: "запрет аренды техники сужает круг участников до крупных буровых компаний",
      },
    ],
    deadline: "2026-10-05",
    specPages: [
      { page: 3, text: "Объём: 12 разведочных скважин колонкового бурения, глубина до 350 м." },
      { page: 6, text: "Исполнитель должен иметь не менее 4 буровых установок в собственности. Арендованная техника не учитывается." },
    ],
  },
  {
    id: "erg-ERG-26-0912",
    externalId: "ERG-26-0912",
    source: "erg",
    sourceUrl: "https://torgi.erg.kz",
    isDemo: true,
    estimated: false,
    title: "Поставка огнеупорных футеровочных материалов",
    titleKz: "Отқа төзімді футерлеу материалдарын жеткізу",
    customer: "АО «ТНК Казхром»",
    contractAmount: 64_500_000,
    advancePercentage: 0,
    deliveryDays: 40,
    paymentDelayDays: 60,
    penaltyRate: 0.0015,
    purchaseCost: 51_000_000,
    cityId: "aktobe",
    cargoTonnes: 48,
    requiredExperienceYears: 2,
    requiredCertificates: ["ISO 9001"],
    hiddenRequirements: [],
    deadline: "2026-09-18",
    specPages: [
      { page: 2, text: "Кирпич магнезиальный — 42 т, мертель — 6 т. Поставка на склад заказчика, г. Актобе." },
      { page: 4, text: "Оплата — 60 календарных дней после поставки. Неустойка 0,15% в день." },
    ],
  },
  {
    id: "bi_group-BI-2026-5520",
    externalId: "BI-2026-5520",
    source: "bi_group",
    sourceUrl: "https://bi-tender.com",
    isDemo: true,
    estimated: false,
    title: "Поставка арматуры А500С для жилого комплекса",
    titleKz: "Тұрғын үй кешеніне А500С арматурасын жеткізу",
    customer: "ТОО «BI Construction»",
    contractAmount: 138_000_000,
    advancePercentage: 20,
    deliveryDays: 25,
    paymentDelayDays: 20,
    penaltyRate: 0.001,
    purchaseCost: 121_000_000,
    cityId: "astana",
    cargoTonnes: 410,
    requiredExperienceYears: 2,
    requiredCertificates: ["СТ РК"],
    hiddenRequirements: [],
    deadline: "2026-09-22",
    specPages: [
      { page: 1, text: "Арматура А500С Ø12–25 — 410 т. Поставка на объект в г. Астана, три партии." },
      { page: 3, text: "Предоплата 20%, остаток — 20 дней после каждой партии." },
    ],
  },
];
