import { CompanyProfile, TenderSpec } from "./types";

/** Digital Twin of the demo SME. */
export const DEMO_COMPANY: CompanyProfile = {
  name: 'ТОО "Алтын Логистик"',
  workingCapital: 52_000_000,
  maxDistanceKm: 900,
  staffSize: 24,
  baseCity: "Алматы",
  taxRate: 0.2,
  monthlyOpex: 4_200_000,
  opexAllocation: 0.35,
  creditRate: 0.24,
  logisticsCostPerKm: 320,
  experienceYears: 4,
  certificates: ["ISO 9001", "СТ РК"],
};

/**
 * Mock lots — the shape an adapter over zakup.gov.kz must produce.
 * Swap this module for a real `TenderSource` without touching the engine.
 */
export const MOCK_TENDERS: TenderSpec[] = [
  {
    id: "TND-2026-0417",
    title: "Поставка компьютерного оборудования для областных школ",
    customer: "Управление образования Алматинской области",
    contractAmount: 84_000_000,
    deliveryDays: 30,
    paymentDelayDays: 30,
    penaltyRate: 0.001,
    guaranteeRate: 0.03,
    purchaseCost: 62_000_000,
    city: "Талдыкорган",
    distanceKm: 260,
    requiredExperienceYears: 3,
    requiredCertificates: ["ISO 9001"],
    hiddenRequirements: [],
    deadline: "2026-09-24",
  },
  {
    id: "TND-2026-0388",
    title: "Капитальный ремонт кровли районной больницы",
    customer: "ГКП «Больница №4»",
    contractAmount: 145_000_000,
    deliveryDays: 75,
    paymentDelayDays: 60,
    penaltyRate: 0.003,
    guaranteeRate: 0.03,
    purchaseCost: 112_000_000,
    city: "Актобе",
    distanceKm: 1_680,
    requiredExperienceYears: 5,
    requiredCertificates: ["ISO 9001", "ISO 45001", "Лицензия СМР III"],
    hiddenRequirements: [
      {
        clause: "Наличие собственного асфальтобетонного завода в радиусе 30 км от объекта",
        severity: "high",
        reason: "требование собственного завода в радиусе 30 км отсекает всех, кроме местного игрока",
      },
      {
        clause: "Опыт по 3 аналогичным объектам именно в данной области",
        severity: "medium",
        reason: "региональная привязка опыта не предусмотрена типовой документацией",
      },
    ],
    deadline: "2026-09-19",
  },
  {
    id: "TND-2026-0451",
    title: "Поставка канцелярских товаров и расходных материалов",
    customer: "Аппарат акима г. Алматы",
    contractAmount: 12_400_000,
    deliveryDays: 20,
    paymentDelayDays: 15,
    penaltyRate: 0.0005,
    guaranteeRate: 0.01,
    purchaseCost: 8_900_000,
    city: "Алматы",
    distanceKm: 18,
    requiredExperienceYears: 1,
    requiredCertificates: [],
    hiddenRequirements: [],
    deadline: "2026-09-16",
  },
  {
    id: "TND-2026-0402",
    title: "Поставка медикаментов для сельских амбулаторий",
    customer: "Управление здравоохранения Жамбылской области",
    contractAmount: 96_000_000,
    deliveryDays: 45,
    paymentDelayDays: 90,
    penaltyRate: 0.002,
    guaranteeRate: 0.03,
    purchaseCost: 71_000_000,
    city: "Тараз",
    distanceKm: 540,
    requiredExperienceYears: 3,
    requiredCertificates: ["GDP", "ISO 9001"],
    hiddenRequirements: [
      {
        clause: "Срок поставки — 5 календарных дней с момента заявки",
        severity: "medium",
        reason: "нереалистичное окно поставки при 90-дневной отсрочке оплаты",
      },
    ],
    deadline: "2026-09-27",
  },
  {
    id: "TND-2026-0433",
    title: "Услуги по вывозу и утилизации ТБО",
    customer: "Отдел ЖКХ г. Шымкент",
    contractAmount: 58_000_000,
    deliveryDays: 180,
    paymentDelayDays: 30,
    penaltyRate: 0.001,
    guaranteeRate: 0.02,
    purchaseCost: 34_000_000,
    city: "Шымкент",
    distanceKm: 690,
    requiredExperienceYears: 2,
    requiredCertificates: ["ISO 14001"],
    hiddenRequirements: [],
    deadline: "2026-10-02",
  },
  {
    id: "TND-2026-0460",
    title: "Поставка спецодежды для коммунальных служб",
    customer: "ГКП «Тазалык»",
    contractAmount: 31_500_000,
    deliveryDays: 25,
    paymentDelayDays: 45,
    penaltyRate: 0.0015,
    guaranteeRate: 0.02,
    purchaseCost: 25_800_000,
    city: "Караганда",
    distanceKm: 1_020,
    requiredExperienceYears: 2,
    requiredCertificates: ["СТ РК"],
    hiddenRequirements: [
      {
        clause: "Ткань конкретного артикула единственного производителя",
        severity: "high",
        reason: "артикул ткани указан так, что подходит продукция ровно одного поставщика",
      },
    ],
    deadline: "2026-09-21",
  },
];
